$(window).scroll(function(){
    var top = $(this).scrollTop();
    if(top >= 100){
        $('nav').addClass("nav_fixed");
        $('.i1').css('top','13.5%');

    }
    else{
        $('nav').removeClass("nav_fixed");
        $('.i1').css('top','10%');
    }
})
$(document).ready(function(){
    $('.open_nav').click(function(){
        $('.menu-link').toggle(1000);
    });
    $('#all').click(function(){
        $('.gallery-item').show(1000);
        $('#im3').css('margin-right','0');
        $('#im6').css('margin-right','0');
        $('#im4').css('margin-right','30px');
        $('#im8').css('margin-right','30px');
        $('#all').addClass("add_bg");
        $('#manag').addClass("rem_bg");
        $('#mark').addClass("rem_bg");
        $('#cons').addClass("rem_bg");
        $('#all').removeClass("rem_bg");
    });
    $('#mark').click(function(){
        $('#im1').show(1000);
        $('#im2').hide(1000);
        $('#im3').show(1000);
        $('#im4').show(1000);
        $('#im5').hide(1000);
        $('#im6').show(1000);
        $('#im7').hide(1000);
        $('#im8').hide(1000);
        $('#im3').css('margin-right','30px');
        $('#im4').css('margin-right','0');
        $('#im6').css('margin-right','30px');
        $('#mark').addClass("add_bg");
        $('#manag').addClass("rem_bg");
        $('#all').addClass("rem_bg");
        $('#cons').addClass("rem_bg");
        $('#mark').removeClass("rem_bg");
    });
    $('#manag').click(function(){
        $('#im1').show(1000);
        $('#im2').hide(1000);
        $('#im3').show(1000);
        $('#im4').hide(1000);
        $('#im5').hide(1000);
        $('#im6').show(1000);
        $('#im7').hide(1000);
        $('#im8').show(1000);
        $('#im9').show(1000);
        $('#im3').css('margin-right','30px');
        $('#im6').css('margin-right','0');
        $('#im8').css('margin-right','30px');
        $('#manag').addClass("add_bg");
        $('#all').addClass("rem_bg");
        $('#mark').addClass("rem_bg");
        $('#cons').addClass("rem_bg");
        $('#manag').removeClass("rem_bg");
    });
    $('#cons').click(function(){
        $('#im1').show(1000);
        $('#im2').hide(1000);
        $('#im3').show(1000);
        $('#im4').show(1000);
        $('#im5').show(1000);
        $('#im6').hide(1000);
        $('#im7').hide(1000);
        $('#im8').show(1000);
        $('#im9').hide(1000);
        $('#im3').css('margin-right','30px');
        $('#im4').css('margin-right','0');
        $('#im8').css('margin-right','0');
        $('#cons').addClass("add_bg");
        $('#manag').addClass("rem_bg");
        $('#mark').addClass("rem_bg");
        $('#all').addClass("rem_bg");
        $('#cons').removeClass("rem_bg");
    });
  })